minetest.after(1, function()
	for _,ore in ipairs({
		"default:stone_with_coal",
		"default:stone_with_iron",
		"default:stone_with_mese",
		"gemstones:ruby_in_ground",
		"gemstones:diamond_in_ground",
		"gemstones:sapphire_in_ground",
		"orichalcum:orichalcum_ore",
		"titanium:titanium_in_ground",
		"moreores:mineral_copper",
		"moreores:mineral_tin",
		"moreores:mineral_silver",
		"moreores:mineral_gold",
		"moreores:mineral_mithril",
		"technic:mineral_diamond",
		"technic:mineral_uranium",
		"technic:mineral_chromium",
		"technic:mineral_zinc",
		"glooptest:mineral_kalite",
		"glooptest:mineral_alatro",
		"glooptest:mineral_talinite",
		"glooptest:mineral_akalin",
		"glooptest:mineral_arol",
		"glooptest:mineral_desert_iron",
		"glooptest:mineral_desert_coal",
		"unuke:uranium",
		"uranium:uranium_ore",
		"gloopores:mineral_alatro",
		"gloopores:mineral_kalite",
		"gloopores:mineral_arol",
		"gloopores:mineral_talinite",
		"gloopores:mineral_akalin",
		"gloopores:mineral_desert_coal",
		"gloopores:mineral_desert_iron",
		"gems:ruby_ore",
		"gems:emerald_ore",
		"diamonds:diamond_in_ground",
		"gems:mineral_garnet",
		"gems:mineral_aquamarine",
		"gems:mineral_topaz",
		"gems:mineral_diamond",
		"gems:mineral_opal",
		"blox:glowore",
		"birthstones:alexandriteore",
		"birthstones:amethystore",
		"birthstones:aquamarineore",
		"birthstones:diamondore",
		"birthstones:emeraldore",
		"birthstones:garnetore",
		"birthstones:peridotore",
		"birthstones:rubyore",
		"birthstones:sapphireore",
		"birthstones:topazore",
		"birthstones:zirconore",
	}) do
		if minetest.registered_nodes[ore] then
			points_0gb_us.register_ore(ore)
		end
	end
end)


